---
driver: 
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: repo 
    run_list:
      - recipe[monit-ng]
      - recipe[setup]
  - name: source
    excludes:
      - ubuntu-12.04
      - centos-6.6
    run_list:
      - recipe[monit-ng]
      - recipe[setup]
    attributes: { monit: { install_method: source } }
