driver:
  name: vagrant

platforms:
  - name: ubuntu-10.04
    run_list: apt
  - name: ubuntu-12.04
    run_list: apt
  - name: ubuntu-13.04
    run_list: apt
  - name: ubuntu-13.10
    run_list: apt

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[ubuntu]